### ISSUE TITLE
Rails5 support

### ISSUE THREAD

**Issue by lgromanowski** [bradurani/pg-eyeballs#3]
Hi,
thank you for this cool gem! Could you please add support for rails5?

**Comment by lgromanowski** [comment]
It seems that gem is working with rails5 after removing activerecord version check in gemspec file :)

**Comment by bradurani** [comment]
Nice, would you like to contribute by making a pull request with this change? If not, I can do it

**Comment by bradurani** [comment]
Actually, I don't think this work with Rails 5. I'm not sure if it's the change I merged into master today, or something else

**Comment by bradurani** [comment]
I've fixed this, and added appraisals test suites to make sure it keeps working. Cutting new release now.

**Comment by lgromanowski** [comment]
Great, thanks! :)
